---
- hosts: webserver
  emote_user: root
  vars_files:
          - "vars/{{env}}_dev_vars.yml"
          - "vars/{{env]]_secret.yml"
  tasks:
    - name: Create new users
      user:
         name: "{{ item.username}}"
         password: "{{ 'toto' | password_hash('sha512') }}"
         createhome: yes
         loop:
                 - username: "{{username1}}" 
                   password: "{{password1}}"
                   username: "{{username2}}"
                   password: "{{password2}}"
         register: recap
         when: ansible_facts['distribution'] = "Ubuntu"
 
    - name: ok
           debug:
             msg: "{{recap}}"


