---
- hosts: webserver
  remote_user: root
  tasks:
     - name: debug
       debug:
           msg: "Bonjour ici l'environonnement"
- hosts: dbserver
  remote_user: root
  tasks:
       - name: ensure is installed
         apt:
           name: vim
           state: present
