---
- hosts: webserver
  remote_user: root
  tasks:
   - name: debug
     debug:
       msg: "bonjour ici l'environement qui fonctionne"
       
- hosts: dbserver
  remote_user: root
  tasks:
   - name: "ensure is installed"
     apt:
       name: vim
       state: present

